### ISSUE TITLE
Managing residential peak usage over 3 phases

### ISSUE THREAD

**Issue by Nickdejonghe** [SmartEVSE/SmartEVSE-3#35]
The smart mode limits the charging current if the mains setting is exceeded. As of beginning of 2023, the Belgian energy price will depend on the peak usage.
Is it possible to limit the charging current in function of the total current used, in other words, the sum of the phases. The mains parameter is applied to each phase, making this impossible.

**Comment by mstegen** [comment]
I have had this request before from Belgian customers.
in my current beta version, i added a 'Capacity' menu option, which allows you to set the max current draw on the sum of all phases. The SmartEVSE will then adjust the current to the EV so that the peak will be limited to this setting.
This works only in Smart Mode.

I have attached the beta firmware.
[firmware.zip](https://github.com/SmartEVSE/SmartEVSE-3/files/10084278/firmware.zip)

**Comment by Nickdejonghe** [comment]
Fantastic, I’ll try it out. Many thanks. NickOp 24 nov. 2022 om 12:58 heeft Michael Stegen ***@***.***> het volgende geschreven:﻿
I have had this request before from Belgian customers.
in my current beta version, i added a 'Capacity' menu option, which allows you to set the max current draw on the sum of all phases. The SmartEVSE will then adjust the current to the EV so that the peak will be limited to this setting.
This works only in Smart Mode.
I have attached the beta firmware.
firmware.zip

**Comment by Nickdejonghe** [comment]
Upgrade working, I can see the additional parameters, but the home display shows access denied?

**Comment by mstegen** [comment]
Ah, I'm working on the lock/unlock functions right now.. a bug. one moment...

**Comment by mstegen** [comment]
@Nickdejonghe please test the latest firmware, i fixed the access denied bug. Thanks.

**Comment by Nickdejonghe** [comment]
It all seems to work fine now. Tx!

**Comment by Nickdejonghe** [comment]
The capacity feature works fine, but I think it could be further improved, at least for the Belgian market. In the current implementation, the charging stops immediately when the capacity setting is exceeded. If you have a device in the home that pulls a high current for short times (such as a quooker, a pump, an expresso machine etc) the charging stops every time and after several charging interruptions, the car quits the loading attemps.
The only way around today is to set the capacity high enough, but then it looses it's purpose to limit the peak utilization.

The peak power utilization in Belgium is defined as the average over a 15 minute interval. Introducing a configurable timer would solve this problem. Instead of stopping the loading proces when the capacity is exceeded, you start a timer and recheck the capacity after. If still exceeded, the loading proces can be stopped.

I would be a great feature to control peak utilization and costs, and a real value-add for customers in the Belgian market!

**Comment by mstegen** [comment]
If there is a peak in current draw the SmartEVSE will first try to reduce the EV charging current, If it's not possible to lower it further, then it will stop charging after 6 seconds.
But your suggestions make sense, i'll look into a configurable timer.

**Comment by Nickdejonghe** [comment]
Thanks, that would really be great. The peak currents usually lasts for 5 to 30s, so loading aborts. A timer could resolve this indeed

**Comment by Moasis3141** [comment]
Will this new firmware be released soon, or should I install the beta?

**Comment by ldpoorter** [comment]
I also installed the beta to use this capacity feature, and it works perfect here too. Thank you for implementing this! But indeed a configurable timer would be nice (just like de "STOP" parameter in solar mode in fact): this would make it possible to lower the capacity value (and thus a cheaper bill) without stopping the charging much.
Do you still plan on implementing this?

**Comment by dingo35** [comment]
I am starting to work on this, do I still have your cooperation for testing this, since it has been some time...?

**Comment by Nickdejonghe** [comment]
Hi,Absolutely, meanwhile I’ve implemented a workaround through home assistant scripting, but far from ideal as I can only switch from smart to solar and off. BrNickOp 31 mei 2024 om 14:01 heeft dingo35 ***@***.***> het volgende geschreven:﻿
I am starting to work on this, do I still have your cooperation for testing this, since it has been some time...?

**Comment by dingo35** [comment]
Ok guys, first of all, Michael Stegen and I independently from eachother developed this "Capacity Rate Limiting" functionality in parallel; somehow my version ended up in 3.6.0 (not because it was better, but it was part of a bigger part of software we merged), so its basic behaviour may have changed; other users (of the Serkri distribution) tested "my" version and were happy with it, but YMMV.

So could you please look at this test version thoroughly :
[4579c131ae3.zip](https://github.com/user-attachments/files/15513881/4579c131ae3.zip)
[4579c131ae3.zip](https://github.com/user-attachments/files/15513881/4579c131ae3.zip)

In the docs you see what to expect:
+SUM MAINS     (only appears when a MAINSMET is configured):
               Maximum allowed Mains Current summed over all phases: 10-600A
               This is used for the EU Capacity rate limiting, currently only in Belgium
 
+SUM STOP      (only appears when SUM MAINS is configured other value then 600A):
+              Nr of minutes before we stop charging when SUM MAINS is exceeded.
+              This is used for the EU Capacity rate limiting, currently only in Belgium
+

**Comment by dingo35** [comment]
I removed the test version because I found a bug in it, to be continued...

**Comment by dingo35** [comment]
[9f1360b527bf5.zip](https://github.com/user-attachments/files/15530147/9f1360b527bf5.zip)

Please test!

**Comment by devdems** [comment]
Isn't this already implemented with maxsummains? I'm using that in Slovenia as we have the same requirements as in Belgium. I'm configuring this value in HA and pushing it to EVSE. It works without an issue so that EVSE is changing the charging the current to not exceed the set limit.

**Comment by dingo35** [comment]
Please read the thread thoroughly before you comment; its about a timer thats added.

**Comment by devdems** [comment]
@dingo35 stop being a smartass. You must be a hoot at the parties! 

@Nickdejonghe your best bet is to get the current average from P1 registers because your meter keeps track of the average consumption over a set period that is set to 15min in most countries. The problem I see with using the timer is that if you exceed the power only for a couple of seconds you can get into penalties as your average in 15 min will be more than allowed. 

![image](https://github.com/SmartEVSE/SmartEVSE-3/assets/8215353/65440391-ca9b-4e79-bb4f-cb83ea47f53a)

**Comment by Karel311** [comment]
I think a user adjustable countdown timer before suspend charging  could be useful since 6 seconds can be short at times (e.g.: between 6s and 15minutes). Other solutions will  complicate the code too much I guess. 

to give you an idea of the Belgian situation: 1 kwh extra consumption in your peak current over a 1 year period will cost you +/-40 Euro extra.  So charging your vehicle at maximum current can increase your bill by 440 euro  at the end of the year.

My P1 meter also measures the average current value every 15 [minutes.](url)

**Comment by devdems** [comment]
I'm ok with that as long this is configurable and defaulted to false :thumbsup:

**Comment by dingo35** [comment]
I am on the verge of closing this feature request, since everybody is posting but nobody is actually testing ....

**Comment by Karel311** [comment]
> I am on the verge of closing this feature request, since everybody is posting but nobody is actually testing ....

Hi Dingo35

I have tested this.
countdown clock is invisible on the webpage or on the lcd, but it works as expected! Good functionality. 
This way I can make an espresso without pause in charging 👍

**Comment by dingo35** [comment]
Well this test took too long;  the base code has changed so much, that I cant merge this code without breaking other stuff.
I dont like doing stuff twice, so closing this issue.
