### ISSUE TITLE
Load Balancing 16 chargers

### ISSUE THREAD

**Issue by ostium** [SmartEVSE/SmartEVSE-3#46]
Hello,

Will it be possible to reach 16 chargers with balancing?

Just change the maximum from 8 to 16 and it will work? or will more structural changes to the code be required?

Thanks a lot for the help. Greetings

**Comment by mstegen** [comment]
No that is currently not possible. address 1-8 are reserved for controllers, 9 is the 'broadcast' address 10 is the Sensorbox, so that would mean you have to rewrite the code.
And there is another problem. Polling the controllers takes time, irc it takes about 0.2 sec per controller. so at 8 controllers that's 1.6 sec. excluding any Energy meters that are configured for each node. which also have to be read.
The max time is 2 sec. above that and timeouts will occur.
